package pageObjects;

import base.BaseForm;
import base.elements.*;
import org.openqa.selenium.By;
import utils.Log;
import utils.StringUtil;
import utils.TimeUtil;

public class WidgetsPage extends BaseForm {
	private Form sliderForm = new Form("sliderForm", By.xpath("//div[contains(text(),'Slider')]"));
	private Button sliderBtn = new Button("sliderBtn", By.xpath("//span[contains(text(),'Slider')]"));
	private TextBox sliderInput = new TextBox("sliderInput", By.id("sliderValue"));
	private Slider slider = new Slider("slider", By.className("range-slider--primary"));
	private Button datePickerBtn = new Button("datePickerBtn",  By.xpath("//span[contains(text(),'Date Picker')]"));
	private Form datePickerForm = new Form("datePickerForm", By.xpath("//div[contains(text(),'Date Picker')]"));
	private TextBox datePickerDateInput = new TextBox("datePickerDateInput", By.id("datePickerMonthYearInput"));
	private TextBox dateTimePickerInput = new TextBox("dateTimePickerInput", By.id("dateAndTimePickerInput"));
	private Form calendarWindow = new Form("calendarWindow", By.className("react-datepicker__month-container"));
	private Dropdown monthSelect = new Dropdown("monthSelect", By.className("react-datepicker__month-select"));
	private Dropdown yearSelect = new Dropdown("yearSelect", By.className("react-datepicker__year-select"));
	private Label day29 = new Label("day29", By.className("react-datepicker__day--029"));
	private Button progressBarBtn = new Button("progressBarBtn", By.xpath("//span[contains(text(),'Progress Bar')]"));
	private Form progressBarForm = new Form("progressBar", By.xpath("//div[@class='main-header' and contains(text(),'Progress Bar')]"));
	private Button startStopBtn = new Button("startStopBtn", By.id("startStopButton"));
	private Label progressBar = new Label("progressBar", By.xpath("//div[@id='progressBar']//div"));
	private String randomNumStr;
	private int sliderNum = 0;

	public WidgetsPage() {
		super("widgetsPage", By.xpath("//div[@class='main-header' and contains(text(),'Widgets')]"));
	}

	public void openDateCalendar() {
		Log.log().info("DatePickerCalendarForm opens.");
		datePickerDateInput.click();
	}

	public boolean isDateCalendarOpen() {
		return calendarWindow.isOpen();
	}

	public void pickClosest29Fev() {
		Log.log().info("Pick 29 February closest to current day.");
		int closestLeapYear = TimeUtil.getClosestDateWith29Feb();
		yearSelect.clickElementByIntValue(Integer.toString(closestLeapYear));
		monthSelect.clickElementByIntValue("2");
		day29.click();
	}

	public boolean isDatePickerDate29Fev() {
		Log.log().info("In the DatePicker DateInput is 29 February.");
		return datePickerDateInput.getTextFromInput().contains("02/29");
	}

	public boolean isSliderFormOpen() {
		return sliderForm.isOpen();
	}

	public boolean isDatePickerFormOpen() {
		return datePickerForm.isOpen();
	}
	public boolean isProgressBarFormOpen() {
		return progressBarForm.isOpen();
	}

	public void clickDatePickerBtn() {
		Log.log().info("Click DatePickerFormButton.");
		datePickerBtn.click();
	}

	public void clickSliderBtn() {
		Log.log().info("Click SliderFormButton.");
		sliderBtn.clickJS();
	}

	public void clickProgressBarBtn() {
		Log.log().info("Click ProgressBarFormButton.");
		progressBarBtn.clickJS();
	}

	public void clickStartBtn() {
		Log.log().info("Click StartButton.");
		startStopBtn.click();
	}

	public void clickStopBtnAt28Percent() {
		Log.log().info("Click StopButton at 28%.");
		int percent = getProgressBarTextInt();
		while(percent < 28) {
			percent = getProgressBarTextInt();
		}
		startStopBtn.click();
	}

	public int getProgressBarTextInt() {
		return progressBar.getAriaValueNowInt();
	}

	public boolean isProgressBarValueBetween28And30() {
		Log.log().info("ProgressBarValue is in [28;30].");
		if(progressBar.getAriaValueNowInt() >= 28 && progressBar.getAriaValueNowInt() <=30)
			return true;
		return false;
	}

	public boolean isSliderNumEqualToGeneratedNum() {
		Log.log().info("Number near slider equals to sent autogenerated number.");
		return randomNumStr.equals(sliderInput.getTextFromInput());
	}

	public boolean isDatePickerDateActual() {
		Log.log().info("The date in DatePickerForm DateInput is actual.");
		return datePickerDateInput.getTextFromInput().equals(TimeUtil.getCurrentMonthDayYear());
	}

	public boolean isDatePickerDateTimeActual() {
		Log.log().info("The date and time in DatePickerForm DateTimeInput is actual.");
		return dateTimePickerInput.getTextFromInput().equals(TimeUtil.getCurrentDateTime());
	}

	public void moveSliderToZero() {
		slider.click();
		sliderNum = Integer.parseInt(sliderInput.getTextFromInput());
		for(int i=0; i<=sliderNum; i++) {
			slider.moveSliderToLeft();
		}
	}

	public void setRandomNumToSlider() {
		Log.log().info("Send random number to SliderInput.");
		randomNumStr = StringUtil.getRandomNumString0to100();
		int randomNum = Integer.parseInt(randomNumStr);
		for(int i=0; i<randomNum; i++) {
			slider.moveSliderToRight();
		}
	}
}