package tests;

import base.BaseTest;
import browser.Browser;
import browser.BrowserConfig;
import org.testng.Assert;
import org.testng.Reporter;
import org.testng.annotations.Test;
import pageObjects.MainPage;
import pageObjects.WidgetsPage;

public class TestCase5SliderProgressBar extends BaseTest {
	private MainPage mainPage;
	private WidgetsPage widgetsPage;

	@Test(priority = 1)
	void testStep1() {
		log("sfasdasdd");
		Reporter.log("\n5 test case started.", true);
		Reporter.log("\n1/6", true);
		Reporter.log("Go to MainPage.", true);
		Browser.getBrowserInstance();
		Browser.goToUrl(BrowserConfig.getHomePageAddress());
		Reporter.log("MainPage opens.", true);
		mainPage = new MainPage();
		Assert.assertTrue(mainPage.isOpen(), "MainPage not found.");
	}

	@Test(priority = 2)
	void testStep2() {
		Reporter.log("\n2/6", true);
		Reporter.log("Click WidgetsButton.", true);
		mainPage.clickWidgetsBtn();
		Reporter.log("WidgetsPage opens.", true);
		widgetsPage = new WidgetsPage();
		Assert.assertTrue(widgetsPage.isOpen(), "WidgetsPage not found.");
		Reporter.log("Click SliderButton.", true);
		widgetsPage.clickSliderBtn();
		Reporter.log("SliderForm opens.", true);
		Assert.assertTrue(widgetsPage.isSliderFormOpen(), "SliderForm not found.");
	}

	@Test(priority = 3)
	void testStep3() {
		Reporter.log("\n3/6", true);
		Reporter.log("Send random number to SliderInput.", true);
		widgetsPage.moveSliderToZero();
		widgetsPage.setRandomNumToSlider();
		Reporter.log("Number near slider equals to sent autogenerated number.", true);
		Assert.assertTrue(widgetsPage.isSliderNumEqualToGeneratedNum(), "SliderLabelNumber not equal to the generated number.");
	}

	@Test(priority = 4)
	void testStep4() {
		Reporter.log("\n4/6", true);
		Reporter.log("Click ProgressBarButton.", true);
		widgetsPage.clickProgressBarBtn();
		Reporter.log("ProgressBarForm opens.", true);
		Assert.assertTrue(widgetsPage.isProgressBarFormOpen(), "ProgressBarForm not found.");
	}

	@Test(priority = 5)
	void testStep5() {
		Reporter.log("\n5/6", true);
		Reporter.log("Click StartButton.", true);
		widgetsPage.clickStartBtn();
	}

	@Test(priority = 6)
	void testStep6() {
		Reporter.log("\n6/6", true);
		Reporter.log("Click StopButton.", true);
		widgetsPage.clickStopBtnAt28Percent();
		Reporter.log("ProgressBarValue is in [28;30].", true);
		Assert.assertTrue(widgetsPage.isProgressBarValueBetween28And30(), "ProgressBarValue not in[28;30].");
	}
}